# Generated by Django 5.0.6 on 2026-05-01 20:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='Disciplina')),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Médio'), ('hard', 'Difícil')], default='medium', max_length=10)),
                ('time_limit', models.PositiveIntegerField(default=30, verbose_name='Tempo limite (min)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Simulado',
                'verbose_name_plural': 'Simulados',
                'db_table': 'simulados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement', models.TextField(verbose_name='Enunciado')),
                ('option_a', models.TextField(verbose_name='Alternativa A')),
                ('option_b', models.TextField(verbose_name='Alternativa B')),
                ('option_c', models.TextField(verbose_name='Alternativa C')),
                ('option_d', models.TextField(verbose_name='Alternativa D')),
                ('correct_option', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, verbose_name='Resposta correta')),
                ('explanation', models.TextField(blank=True, verbose_name='Explicação')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('simulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='simulados.simulado')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'db_table': 'questions',
                'ordering': ['order', 'id'],
            },
        ),
    ]
