# Generated by Django 5.0.6 on 2026-05-01 20:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chosen_option', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, null=True, verbose_name='Alternativa escolhida')),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'db_table': 'attempt_answers',
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Acertos')),
                ('total_questions', models.PositiveIntegerField(verbose_name='Total de questões')),
                ('time_taken', models.PositiveIntegerField(default=0, verbose_name='Tempo gasto (seg)')),
                ('status', models.CharField(choices=[('in_progress', 'Em progresso'), ('completed', 'Finalizado')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('simulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='simulados.simulado')),
            ],
            options={
                'verbose_name': 'Tentativa',
                'verbose_name_plural': 'Tentativas',
                'db_table': 'attempts',
                'ordering': ['-started_at'],
            },
        ),
    ]
